version: "3.8"

services:
  # 1. BACKEND APP (GO)
  backend:
    build: .
    container_name: inspacemap_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      # Override DB_HOST agar mengarah ke nama service docker
      - DB_HOST=db
      - MINIO_ENDPOINT=http://minio:9000

  # 2. DATABASE (POSTGRESQL)
  db:
    image: postgres:15-alpine
    container_name: inspacemap_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" # Expose ke host agar bisa diakses DBeaver/PgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. OBJECT STORAGE (MINIO)
  minio:
    image: minio/minio:latest
    container_name: inspacemap_storage
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - "9000:9000" # API Port (S3 Compatible)
      - "9001:9001" # Web Console Port
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    # Healthcheck untuk memastikan MinIO siap sebelum dipakai (Opsional tapi bagus)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

# Volume persisten agar data tidak hilang saat container dimatikan
volumes:
  postgres_data:
  minio_data:
